### ISSUE TITLE
Triage action is failing; missing module jwt

### ISSUE THREAD

**Issue by jlewi** [kubeflow/code-intelligence#114]
Here's an error from a failed action

```
/usr/bin/docker run --name kubeflowkubeflowtriage_b68cc1 --label 488dfb --workdir /github/workspace --rm -e INPUT_ISSUE_NUMBER -e INPUT_GITHUB_PERSONAL_ACCESS_TOKEN -e INPUT_NEEDS_TRIAGE_PROJECT_CARD_ID -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/manifests/manifests":"/github/workspace" kubeflow/kubeflow-triage
Traceback (most recent call last):
  File "/py/issue_triage/triage_for_action.py", line 1, in <module>
    from issue_triage.triage import IssueTriage
  File "/py/issue_triage/triage.py", line 2, in <module>
    from code_intelligence import graphql
  File "/py/code_intelligence/graphql.py", line 2, in <module>
    from code_intelligence import github_app
  File "/py/code_intelligence/github_app.py", line 13, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
##[error]Docker run failed with exit code 1
```

Looks like the image is missing pyjwt

**Comment by jlewi** [comment]
Failing now because of missing tqdm

```
Run kubeflow/code-intelligence/Issue_Triage/action@master
/usr/bin/docker run --name kubeflowkubeflowtriage_7c0f97 --label 488dfb --workdir /github/workspace --rm -e INPUT_ISSUE_NUMBER -e INPUT_GITHUB_PERSONAL_ACCESS_TOKEN -e INPUT_NEEDS_TRIAGE_PROJECT_CARD_ID -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/kfctl/kfctl":"/github/workspace" kubeflow/kubeflow-triage
Traceback (most recent call last):
  File "/py/issue_triage/triage_for_action.py", line 1, in <module>
    from issue_triage.triage import IssueTriage
  File "/py/issue_triage/triage.py", line 2, in <module>
    from code_intelligence import graphql
  File "/py/code_intelligence/graphql.py", line 2, in <module>
    from code_intelligence import github_app
  File "/py/code_intelligence/github_app.py", line 15, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
##[error]Docker run failed with exit code 1
```

We should stop using "latest" tag and instead use some tag like "live" which we only set on an action after validating the image.

**Comment by jlewi** [comment]
Fixed.
