### ISSUE TITLE
Ensemble repo specific and non-repo specific models

### ISSUE THREAD

**Issue by jlewi** [kubeflow/code-intelligence#70]
Currently the label bot has two models

1. A generic model trained on all repositories that only handles labels bug, question, feature
1. (Optionally) A repo specific model for repo specific labels

Currently the code uses one model or the other
https://github.com/machine-learning-apps/Issue-Label-Bot/blob/536e8bf4928b03d522dd021c0464587747e90a87/flask_app/app.py#L143

In particular if a repo specific model is available it is used to predict the kind label. This is undesirable because the repo specific model usually does much worse when predicting the kind label compared to the repo specific model.

What we'd prefer to do is use the generic model for the kind label to predict the kind label and the repo specific model to predict other labels.

We can probably achieve this just by modifying the code here
https://github.com/kubeflow/code-intelligence/blob/23ff8f6a59b5f0a7eff12ca62b5aa152d993806d/py/label_microservice/worker.py#L128

To also use the generic model to compute the kind label. Basically by copying this code
https://github.com/machine-learning-apps/Issue-Label-Bot/blob/536e8bf4928b03d522dd021c0464587747e90a87/flask_app/app.py#L164

**Comment by jlewi** [comment]
Now that we are moving to an asynchronous model based on pubsub we could easily have multiple models operating independently just by creating multiple workers with different pubsub subscriptions.

If the models are operating independently we'd have to think about how label combination would be applied. e.g. suppose 1 model applies the label kind/bug but a different model predicts kind/question. How should these be combined? If the workers are operating independently would we remove the previous models labels?

**Comment by jlewi** [comment]
One of the issues that @hamelsmu raised in the code review #82 is that the probabilities for different models won't be on the same scale.  So simply take the max probability from the two models for the same label may not make sense.

I think this also means that each model should have its own confidence thresholds. For the generic model the thresholds are set here
https://github.com/machine-learning-apps/Issue-Label-Bot/blob/536e8bf4928b03d522dd021c0464587747e90a87/flask_app/app.py#L42

One way to combine the models would be for each model apply the respective thresholds and then take the union of the labels.

**Comment by jlewi** [comment]
Now that the code is complete we need to deploy it.

I think we want to create a new Kubeflow cluster to deploy the updated microservices. Currently we have the different microservices each running in their own cluster in project **issue-label-bot-dev**.

* **github-api-cluster** - This cluster appears to be running the issue embedding microservice.
   * After the code changes; this should now be a microservice in the same cluster as the pubsub
     workers.

* **workers** - This cluster appears to be running the pubsub workers that are handling the production topic.

* **github-mlapp-test** This appears to be the staging cluster
   * Per [setup_staging_cluster.md](https://github.com/kubeflow/code-intelligence/blob/master/Label_Microservice/docs/set_up_staging_cluster.md) this appears to be a staging instance that is also running an instance of the flask app that handles the GitHub webhooks.

* **issue-label-bot-dev-kf** This is a KF cluster used for development.

I think we should do the following

* Create a new 0.7 KF cluster
* Use separate namespaces for prod, staging, dev
* Delete the clusters listed above. 
  * See #35
* Create a new staging process for the app
   * See #87

**Comment by jlewi** [comment]
Created a 0.7 deployment.

* **project**: issue-label-bot-dev
* **cluster**: issue-label-bot
* **zone**: us-east1-d

**Comment by jlewi** [comment]
* Create a KF profile named `kaniko` to create a namespace to run kaniko builds for skaffold

   * Due to GoogleContainerTools/skaffold#3442 we need to run skaffold builds in namespace without istio side car injection

Disable istio injection in this namespace

```
kubectl label namespace kaniko istio-injection=disabled --overwrite=true
```

* I used the GKE UI to bump the node auto-provisioning settings; increased the number of CPUs to 48.

  * otherwise it couldn't provision new nodes to schedule my kaniko builds.

* Per kubeflow/kubeflow#4259 we need to update the node auto-provisioner node scope

    ```
    gcloud --project=issue-label-bot-dev beta container clusters update issue-label-bot --enable-autoprovisioning --autoprovisioning-scopes=https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring,https://www.googleapis.com/auth/devstorage.read_only
    ```

**Comment by jlewi** [comment]
* skaffold's kaniko jobs won't work with workload identity so we need to copy the GCP secret to the kaniko namespace ( see GoogleContainerTools/skaffold#3468)

    ```
   NAMESPACE=kaniko
   SOURCE=kubeflow
   NAME=user-gcp-sa
   SECRET=$(kubectl -n ${SOURCE} get secrets ${NAME} -o jsonpath="{.data.${NAME}\.json}" | base64 -d)
   kubectl create -n ${NAMESPACE} secret generic ${NAME} --from-literal="${NAME}.json=${SECRET}"
    ```

**Comment by jlewi** [comment]
* Create a Kubeflow profile corresponding to namespace `label-bot-dev`

* Load the github-app secret
  
   ```
   python3 scripts/create_secrets.py create-dev
   ```

* Disable istio sidecar injection because istio seems to be interferring with the services

   ```
   kubectl label namespace label-bot-dev istio-injection=disabled --overwrite=true
   ```

    * The embedding service was failing its readiness probe; it was returning 503s/

**Comment by jlewi** [comment]
Grant pubsub permissions

```
PROJECT=issue-label-bot-dev
ACCOUNT=issue-label-bot-user@issue-label-bot-dev.iam.gserviceaccount.com
gcloud projects add-iam-policy-binding ${PROJECT} --role roles/pubsub.editor  --member "serviceAccount:${ACCOUNT}"
```

**Comment by jlewi** [comment]
* Dev version is working lets setup prod
* Create `label-bot-prod` profile
* Disable ISTIO 
   ```
   kubectl label namespace label-bot-prod istio-injection=disabled --overwrite=true
   ```
* Create the GitHub app secret
   
   ```
   python3 scripts/create_secrets.py create-prod
   ```

**Comment by jlewi** [comment]
Update and deploy the production version of the label microservice

1. Build the image

    ```
    skaffold build 
    ```

1. Set the image

    ```
kustomize edit set image gcr.io/issue-label-bot-dev/bot-worker=gcr.io/issue-label-bot-dev/bot-worker:a5fbacb@sha256:06d533735b257a0346ac54a9a040882a1dd6b0ad0d054fac0075d06191d9a9a7
    ```
1. Deploy it

     ```
     cd Label_Microservice/deployment/overlays/prod
     kustomize build | kubectl apply -f -
     ```
1. Repeat the above steps for the issue embedding microservice

**Comment by jlewi** [comment]
Deleted the **github-mlapp-test** cluster

**Comment by jlewi** [comment]
Delete the old clusters because we no longer want to run the older versions of the service

Delete clusters 
* **github-api-cluster**
* **workers**

**Comment by jlewi** [comment]
Lets delete the old kubeflow deployment.

issue-label-bot-dev-kf

**Comment by jlewi** [comment]
Here's an issue that was labeled by the bot in the last 24 hours.
https://github.com/kubeflow/kubeflow/issues/4613

It doesn't look like it is using the new code because the comment isn't a markdown table with probabilities.
https://github.com/kubeflow/kubeflow/issues/4613#issuecomment-570131094

**Comment by jlewi** [comment]
I'm seeing 3 issues.

1. After successfully generating a bunch of predictions we start to see exceptions like the following

   ```
    Traceback (most recent call last):
    File "/py/label_microservice/worker.py", line 145, in callback
      predictions = self._predictor.predict(data)
    File "/py/label_microservice/issue_label_predictor.py", line 152, in predict
      model_name=data.get("model_name"))
    File "/py/label_microservice/issue_label_predictor.py", line 114, in predict_labels_for_issue
      model_name, data.get("title"), data.get("body"))
    File "/py/label_microservice/issue_label_predictor.py", line 74, in predict_labels_for_data
      predictions = model.predict_issue_labels(title, body)
    File "/py/label_microservice/combined_model.py", line 34, in predict_issue_labels
      latest = m.predict_issue_labels(title, text)
    File "/py/label_microservice/universal_kind_label_model.py", line 84, in predict_issue_labels
      probs = self.model.predict(x=[vec_body, vec_title]).tolist()[0]
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
      use_multiprocessing=use_multiprocessing)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 723, in predict
      callbacks=callbacks)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 394, in model_iteration
      batch_outs = f(ins_batch)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
      run_metadata=self.run_metadata)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
      run_metadata_ptr)
    tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_5/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/dense_5/bias/N10tensorflow3VarE does not exist.
   ```

      * Full logs 
[label-bot-worker-5c8967dc7c-vm9bd.log.txt](https://github.com/kubeflow/code-intelligence/files/4018397/label-bot-worker-5c8967dc7c-vm9bd.log.txt)

       * As a quick fix we could try catching the FailedPreconditionErrors and crashing the process

1. It looks like issues are getting stuck in the pusub queue because of issues with workload identity in the workers (see #88)

1. The front end isn't forwarding all issues see; https://github.com/machine-learning-apps/Issue-Label-Bot/blob/master/flask_app/forwarded_repo.yaml

**Comment by jlewi** [comment]
Deployed to prod; based on kubeflow/kubeflow#4618 looks like its working.

**Comment by jlewi** [comment]
Here's an initial report of how we are doing:
https://storage.cloud.google.com/issue-label-bot-dev_reports/metrics_2020_0406.html
