### ISSUE TITLE
Issue Triage Action Is Failing Missing Pytz

### ISSUE THREAD

**Issue by jlewi** [kubeflow/code-intelligence#96]
The issue triage action is failing because the import `pytz` can not be found.

```
Run kubeflow/code-intelligence/Issue_Triage/action@master
/usr/bin/docker run --name kubeflowkubeflowtriage_81c626 --label 671ee6 --workdir /github/workspace --rm -e INPUT_ISSUE_NUMBER -e INPUT_GITHUB_PERSONAL_ACCESS_TOKEN -e INPUT_NEEDS_TRIAGE_PROJECT_CARD_ID -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/kubeflow/kubeflow":"/github/workspace" kubeflow/kubeflow-triage
Traceback (most recent call last):
  File "/py/issue_triage/triage_for_action.py", line 1, in <module>
    from issue_triage.triage import IssueTriage
  File "/py/issue_triage/triage.py", line 2, in <module>
    from code_intelligence import graphql
  File "/py/code_intelligence/graphql.py", line 2, in <module>
    from code_intelligence import util
  File "/py/code_intelligence/util.py", line 4, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
##[error]Docker run failed with exit code 1
```
/assign @jlewi

**Comment by jlewi** [comment]
New image was built.
https://hub.docker.com/r/kubeflow/kubeflow-triage

Still failing.

```
Update Kanban6s
##[error]Docker run failed with exit code 1
Run kubeflow/code-intelligence/Issue_Triage/action@master
/usr/bin/docker run --name kubeflowkubeflowtriage_345db4 --label 671ee6 --workdir /github/workspace --rm -e INPUT_ISSUE_NUMBER -e INPUT_GITHUB_PERSONAL_ACCESS_TOKEN -e INPUT_NEEDS_TRIAGE_PROJECT_CARD_ID -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/kubeflow/kubeflow":"/github/workspace" kubeflow/kubeflow-triage
Traceback (most recent call last):
  File "/py/issue_triage/triage_for_action.py", line 1, in <module>
    from issue_triage.triage import IssueTriage
  File "/py/issue_triage/triage.py", line 2, in <module>
    from code_intelligence import graphql
  File "/py/code_intelligence/graphql.py", line 2, in <module>
    from code_intelligence import util
  File "/py/code_intelligence/util.py", line 7, in <module>
    import json_log_formatter
ModuleNotFoundError: No module named 'json_log_formatter'
##[error]Docker run failed with exit code 1
```
